// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD09H_bIhw8Cb5QrK0lSxUaUJDmr1s8k1A',
    appId: '1:1070697801997:web:ff25c554dc4721eb046844',
    messagingSenderId: '1070697801997',
    projectId: 'checkdreamproperty',
    authDomain: 'checkdreamproperty.firebaseapp.com',
    databaseURL: 'https://checkdreamproperty-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'checkdreamproperty.firebasestorage.app',
    measurementId: 'G-JR15SL0CV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbpcuej462lQBJg6uggXijnEShNbdSkI4',
    appId: '1:1070697801997:android:986369bc41a02cb0046844',
    messagingSenderId: '1070697801997',
    projectId: 'checkdreamproperty',
    databaseURL: 'https://checkdreamproperty-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'checkdreamproperty.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrt7pzxk3Hu8InuQoqlIxigj6AQwHNy9Y',
    appId: '1:1070697801997:ios:8f1ed27dc8189540046844',
    messagingSenderId: '1070697801997',
    projectId: 'checkdreamproperty',
    databaseURL: 'https://checkdreamproperty-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'checkdreamproperty.firebasestorage.app',
    iosBundleId: 'com.example.checkdreamproperty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrt7pzxk3Hu8InuQoqlIxigj6AQwHNy9Y',
    appId: '1:1070697801997:ios:8f1ed27dc8189540046844',
    messagingSenderId: '1070697801997',
    projectId: 'checkdreamproperty',
    databaseURL: 'https://checkdreamproperty-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'checkdreamproperty.firebasestorage.app',
    iosBundleId: 'com.example.checkdreamproperty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD09H_bIhw8Cb5QrK0lSxUaUJDmr1s8k1A',
    appId: '1:1070697801997:web:66d7816f015c2c83046844',
    messagingSenderId: '1070697801997',
    projectId: 'checkdreamproperty',
    authDomain: 'checkdreamproperty.firebaseapp.com',
    databaseURL: 'https://checkdreamproperty-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'checkdreamproperty.firebasestorage.app',
    measurementId: 'G-57BZNS7NFC',
  );

}